name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
        

      - name: Build Website 
        working-directory: ./website
        run: npm ci && npm run build --if-present

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo
        working-directory: ./slides
        run: hugo --gc --minify --cleanDestinationDir -d ../website/dist/6443/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        working-directory: ./website
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist